### ISSUE TITLE
assembler breaks on HADD2

### ISSUE THREAD

**Issue by apanqasem** [daadaada/turingas#5]
I was able to successfully install turingas. But when I try to run it with the copy_element example, I get the following error. I wonder if it has something to do with the latest commit. 

```  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 544, in spec_from_file_location
  File "/usr/local/lib/python3.6/dist-packages/turingas-0.1-py3.6.egg/turingas/grammar.py", line 171
    'HADD2' : [{'code' : 0x230, 'rule' : rf'HADD2 {rd}, {rs0}, {rs1};'}, 'lat' : 7],
```

update: it works fine, if I comment out the three half- instructions

**Comment by daadaada** [comment]
I've fixed the syntax error. Thank you for reporting this!
